version: '3'
services:
  app:
    # image: 'jc21/nginx-proxy-manager:latest'
    image: nguyenngochuy/nginx-proxy-manager

    restart: always
    container_name: nginx
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "3"
